name: build

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/*.jar
